@extends('website.layout.layout')
@section('content')
    <style>
        h1{
            font-size: 1.7em !important;
            font-weight: 700 !important;
            padding: 5px 0px 5px 15px;
            border-left: 1px solid #575656;
        }
        
        h2{
            font-size: 1.3em !important;
        }
        
        h3{
            font-size: 1.1em !important;
            border-left: 1px solid #BDB9B9;
            padding: 5px 0px 5px 15px;
        }
@media(max-width:375px)
{
    .privacy h1, .privacy h3 {
    font-size: 18px!important;
}
.privacy p, .privacy ul li {
    font-size: 11px!important;
}
}
          @media only screen and (max-width: 800px) {


            ul{
                padding-left: 10px !important;
                padding-right: 10px !important;
            }

            .legoz{
                padding: 10px !important;
            }

              }
               @media only screen and (max-width: 800px) {
                   .container-fluid .row.legoz {
    margin: -55px 15px 25px 10px !important;
    margin-top: 30px !important;
               }
               .openbutton, img {
    width: 25%;
}
               }
    </style>

    <section class="privacy">
        <div class="container-fluid">
            <div class="row legoz" style="margin-top: 120px; padding: 10px 70px 0px 40px">
                <div class="col-lg-12">
                  
                <h1>
                    TERMS AND CONDITIONS FOR SITE SUPPLY (BUYER)
                </h1> <br>

                <p>
                
                THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES THERE UNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
                
                </p>

                    <p>

                    THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3 (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES) RULES, 2011 THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND TERMS OF USE FOR ACCESS OR USAGE OF THE PLATFORM.
                    </p>


                        <p>
                        By accessing or using the Site Supply Platform (as defined below). You agree to be bound by these Terms. Your agreement with us includes these Terms and the Privacy Policy available at [LINK] (collectively “Agreement”).
                        </p>


                                <br>
                                <p>

                                IF YOU DO NOT AGREE WITH THESE TERMS, THEN PLEASE REFRAIN FROM USING THE PLATFORM. BY ACCESSING OR USING THE PLATFORM, YOU IRREVOCABLY ACCEPT THE AGREEMENT AND AGREE TO ABIDE BY THE SAME (AS UPDATED FROM TIME TO TIME).
                                </p> <br>

                                  <ul style="padding-left: 50px; padding-right:30px">

                                  <li>
                                  <strong> DEFINITIONS</strong> “Site Supply Platform” or “Platform” shall mean Site Supply website made available at [LINK] and the Site Supply mobile application available on Android and iOS.
                                  </li>
                                  <li>
                                 <strong> ELIGIBILITY CRITERIA</strong>
                                 User represent and warrant that they have the right to access or use the Platform. The Platform can only be availed by those individuals or business entities, including sole proprietorship firms, companies and partnerships, which can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un- discharged insolvents etc. are not eligible to use the Platform.
                                  </li>
                                  <li>
                                  <strong>GENERAL DISCLAIMERS</strong>
                                  You shall not acquire, copy, or monitor any portion of the Platform in any way to reproduce or circumvent the navigational structure or presentation of the Platform, to obtain or attempt to obtain any materials, documents, or information through any means not specifically made available through the Platform.
                                  </li>
                                  <br>
                                  SITE SUPPLY RESERVES THE RIGHT TO SUSPEND OR TERMINATE THE ACCOUNT OF A MEMBER OR ANY USER(S) AS DEEMED APPROPRIATE BY SITE SUPPLY AT ITS SOLE DISCRETION. USER(S) AGREE THAT SITE SUPPLY SHALL HAVE NO LIABILITY TO ANY USER(S), INCLUDING LIABILITY IN RESPECT OF CONSEQUENTIAL OR ANY OTHER DAMAGES, IN THE EVENT SITE SUPPLY TAKES ANY OF THE ACTIONS MENTIONED IN THIS PROVISION.
                                        <br>

                                        <li>
                                        <strong>
                                        AMENDMENT TO THESE TERMS
                                        </strong>
                                        Site Supply reserves the right to change, modify, amend, or update these Terms and/ or the Agreement from time to time and such amended provisions of these Terms and/ or the Agreement shall be effective immediately upon being posted on the Platform. If You do not agree to such provisions, You must stop using the Platform with immediate effect. Your continued use of the Platform will be deemed to signify Your acceptance of the amended provisions of these Terms and/ or the Agreement.
                                        </li>

                                        <li>
                                        <strong>
                                        	INTELLECTUAL PROPERTY RIGHTS
                                        </strong>
                                        Site Supply is the sole owner and the lawful licensee of all the rights in and to the Platform and the design, layout, text, images, graphics, sound, video etc. of or made available on the Platform (“Content”). The Content may include trade secrets and other intellectual property rights protected under worldwide copyright and other applicable laws pertaining to intellectual property. All title, interest, ownership and intellectual property rights in the Platform and the Content shall remain in Site Supply, its affiliates or licensor’s of the relevant Content, as the case may be.
                                        </li>
                                    </ul> <br>


                        <p>
                        All rights, not otherwise claimed under these Terms by Site Supply are hereby reserved.
                        </p>
                        <br>

                        <p>
                        Any information or advertisements contained on, distributed through, or linked, downloaded or accessed from the Platform or any offer displayed on the Platform (“Information”) is intended, solely to provide general information for the personal use of the User(s), who fully accept any and all responsibility and liabilities arising from and out of the use of such Information. Site Supply does not represent, warrant or endorse in any manner the accuracy or reliability of such Information, or the quality of any products and/or services obtained by the User(s) as a result of any such Information.
                        </p> <br>

                        <p>
                        The Information is provided “as is” with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of the Information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose. Nothing contained in these Terms shall to any extent substitute for the independent investigations and the sound technical and business judgment of the User(s).
                        </p> <br>

                        <p>
                        In no event shall Site Supply be liable for any direct, indirect, incidental, punitive, or consequential damages of any kind whatsoever with respect to the User(s) use of such product/ service.
                        </p> <br>

                         <ul style="padding-left: 50px; padding-right:30px">
                                <li> <strong>Trademark:</strong>  “Site Supply” and related icons and logos whether registered or unregistered are the trademarks of Site Supply and are protected under applicable copyright, trademark and other proprietary and intellectual property laws. The unauthorized adoption copying, modification, use or publication of these marks is strictly prohibited.</li>
                                <li>
                                <strong>Copyright:</strong>  All Content including Information is copyrighted to Site Supply excluding any third-party content and any links to any third-party websites being made available or contained on the Platform. User(s) may not use any trademark, service mark or logo of any independent third parties without prior written approval from such parties.
                                </li>

                              
                         </ul> <br>


                         <h3>
                         	PARTIES TO THE AGREEMENT
                         </h3> <br>

                         <p>
                         These Terms describe a contractual relationship between Member and Site Supply. Site Supply reserves the right to deny Member and/or User access/terminate access/suspend access to the Platform at its sole discretion without providing any reason whatsoever.
                         </p> <br>


                         <h3>
                         	OUR SERVICES
                         </h3> <br>

                         <p>
                       	The Member may choose to buy the Product(s) listed on the Platform at the price (exclusive of all taxes) and/or by seek quote for Large Scale Orders.
                         </p>

                         <p>
                         	On Conclusion of transaction and completion of successful payment. Site Supply or the Seller shall ship the purchased Products to the Member through a well-known reputed logistics company along with transit insurance (if applicable) or the Site Supply designated logistics partners (as may be shared by Site Supply from time to time).
                         </p> <br>

                         <h3>
                         	PROCESS TO SEEK QUOTE FOR LARGE SCALE ORDERS (applicable to Members)
                          </h3> <br>

                          <p>
                          Member may choose to seek quotes on the Platform to find the best prices at which Site Supply/Seller is willing to sell the Product(s). Site Supply may share the best- selling price (inclusive of all taxes) and the Member chooses to accept or reject the same.
                          </p>
                          <br>
                          <p>
                          The Member will need to share certain additional details of the order as requested on the Products page.
                          </p>

                          <br>

                          <h3>
                          	TERM AND TERMINATION
                          </h3> <br>

                          <p>
                          Site Supply may suspend or terminate User and/or Member use of the Site Supply Platform and/or Service:
                          </p> <br>

                          <p>
                           if it believes, in its sole and absolute discretion that User and/or Member have breached, violated, abused, or unethically manipulated or exploited any term of these Terms or anyway otherwise acted unethically;
                          </p> <br>

                          
                                 <ul style="padding-left: 50px; padding-right:30px">


                                 <li>if it is brought to Site Supply’s notice or if it is discovered that User is under the age of 18 years; or</li>
                                 <li>	Site Supply shall deactivate any dormant Account which has not been accessed for a period of [∙] days; or</li>
                                 <li>	if Site Supply has reasonable grounds to suspect that any information provided by User and/or Member is untrue, inaccurate, not current or incomplete, or not in accordance with these Terms; or</li>
                                 <li>
                                 	accessing data not intended for the User or logging on to a server or Member account the User is not authorised to use; or
                                 </li>
                                 <li>
                                 attempting to probe, scan or test the vulnerability of the system or network or to breach security or authentication measures without authentication; or
                                 </li>
                                 <li>
                                 	accessing or using the Platform without authorisation, in violation of these Terms or in violation of applicable law.
                                 </li>

                                 </ul> <br>


                                    <p>
                                    Site Supply reserves the right to refuse to process transactions/communications by Member with a prior history of questionable charges including without limitation, breach of any agreements or breach/violation of any law or breach of any policy.
                                    </p> <br>


                                    <p style="color:darkgrey">
                                    VIOLATIONS OF SYSTEM OR NETWORK SECURITY MAY RESULT IN CIVIL OR CRIMINAL LIABILITY. SITE SUPPLY WILL INVESTIGATE OCCURRENCES THAT MAY INVOLVE SUCH VIOLATIONS AND COOPERATE WITH LAW ENFORCEMENT AUTHORITIES IN PROSECUTING USERS WHO ARE INVOLVED IN SUCH VIOLATIONS. YOU AGREE NOT TO USE ANY DEVICE, SOFTWARE, OR ROUTINE TO INTERFERE OR ATTEMPT TO INTERFERE WITH THE PROPER WORKING OF THIS PLATFORM OR ANY ACTIVITY BEING CONDUCTED ON THIS PLATFORM.
                                    </p> <br>


                                    <h3>
                                    	NO GUARANTEES
                                    </h3> <br>

                                    <p>
                                    
                                    Among other things, Site Supply does not guarantee that:
                                    </p> <br>

                                     <ul style="padding-left: 50px; padding-right:30px">

                                            <li>The Platform will be accessible without interruption or in a timely, reliable, or fault-free manner; or</li>
                                                <li>	The results obtained through the use of the Platform will be correct and reliable; or</li>
                                                <li>	The quality of the Products, services, information, or other material purchased or obtained by the User through the Platform will meet the User’s expectations.</li>
                                                
                                                
                                     </ul> <br>

                                     <p>
                                     The User shall be solely responsible for damages to his or her data system or for loss of data arising from the download of content from the Platform.
                                     </p> <br>

                                     <p>
                                     No guidance or information, written or oral, obtained from Site Supply or via the Platform, shall constitute any warranty, which has not specifically been stated in these Terms.
                                     </p> <br>


                                     <h3>
                                     	LIMITATION OF LIABILITY
                                     </h3>

                                     <p>
                                     User specifically acknowledges and agrees that in no event shall Site Supply be liable for any direct or indirect damages, including but not limited to, delay, damages caused by unused opportunity on the Platform, loss of profits, goodwill, data, or other financial loss arising out of:
                                     </p>

                                     <br>
                                        <h3>
                                        
                                        	FORCE MAJEURE</h3> <br>

                                            <p>
                                            Site Supply shall not be liable for any damages whatsoever arising out of force majeure or other similar circumstances, directly or indirectly affecting Site Supply and/ or the Platform. Examples of force majeure events are real or potential labour disputes, governmental actions, war or threat of war, sabotage, civil unrest, demonstrations, fire, storm, flooding, explosion, earthquake, provisions or limitations of materials or resources, inability to obtain the relevant authorization, accident, and defect in electricity or telecommunication network. Force majeure or other events beyond Site Supply’s control hindering, delaying or complicating the maintenance of the Platform entitles Site Supply to suspend or limit the Platform until further notice.
                                            </p> <br>

                                            <h3>
                                            	INDEMNITY
                                            </h3> <br>

                                            <p>
                                            The Users shall indemnify, defend, and hold harmless Site Supply and its affiliates, if any, from and against any and all losses, liabilities, claims, suits, proceedings, penalties, interests, damages, demands, costs, and expenses (including legal and statutory fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by Site Supply that arise out of, result from, or in connection with:
                                            </p> <br>

                                            <p>
                                            Notwithstanding anything to the contrary in these Terms, in no event shall Site Supply and its affiliates, if any, be liable to the User or anyone claiming through the User in respect of any subject matter of these Terms under contract, negligence, strict liability or other legal or equitable theory for any special, incidental, indirect, consequential, exemplary or punitive damages, loss of goodwill, loss of revenue, loss of opportunity, loss of anticipated profits, whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not Site Supply has been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty or negligence or any other claim arising out of or in connection with the use of or access of the Platform.
                                            
                                            </p> <br>

                                            <h3>
                                            	USE OF YOUR PERSONAL INFORMATION
                                            </h3>

                                            <br>
                                            <p>
                                            In course of User and/or Member registration on the Platform and use of the Platform, the User and/or Member may be asked to provide certain Personal Information to Site Supply. Site Supply’s information collection and use policies with respect to privacy of such information are set forth in the Privacy Policy available at [●].
                                            </p> <br>

                                            <h3>
                                            	DISCLAIMER AND LIMITATION OF LIABILITIES
                                            </h3> <br>

                                            <p>THIS PLATFORM IS PROVIDED BY SITE SUPPLY ON AN “AS IS” AND “AS AVAILABLE” BASIS. SITE SUPPLY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS PLATFORM OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS PLATFORM. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS PLATFORM IS AT YOUR SOLE RISK. SITE SUPPLY RESERVES THE RIGHT TO WITHDRAW OR DELETE ANY INFORMATION FROM THIS PLATFORM AT ANY TIME IN ITS DISCRETION.</p> <br>
                                            <p>TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, SITE SUPPLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. SITE SUPPLY DOES NOT WARRANT THAT THIS PLATFORM, ITS SERVERS, OR E-MAIL SENT FROM SITE SUPPLY ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. SITE SUPPLY WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS PLATFORM, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE AND CONSEQUENTIAL DAMAGES.</p> <br>


                                              <h3>
                                              	SEVERABILITY</h3> <br>

                                                  <p>
                                                  If any provision of these Terms is found by a competent court or other binding authority to be invalid, You agree that every attempt shall be made to give effect to the parties intentions as reflected in that provision, and the remaining provisions contained in the Terms shall continue in full force and effect.
                                                  </p>      <br>

                                                  <h3>
                                                  	GOVERNING LAW
                                                  </h3> <br>

                                                  <p>
                                                  The laws of India shall govern these Terms of Use, regardless of location. User and/or Member hereby expressly consent to the exclusive jurisdiction of the courts of Gurugram, India, for all matters or disputes arising out of or relating to these Terms or access or use of the Platform/service.
                                                  </p>
                                                  <br>

                                                  <h3>
                                                  	MISCELLANEOUS
                                                  </h3> <br>
                                                   <ul style="padding-left: 50px; padding-right:30px">
                                                   <li>Headings for any section of the Agreement are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section.</li>
                                                   <li>Site Supply shall have the right to assign its obligations and duties in this Agreement to any person or entity.</li>
                                                   <li>All calls to Site Supply are completely confidential. However, Your call may be recorded to ensure quality of service. Further, for training purposes and to ensure excellent customer service, calls from Site Supply may be monitored and recorded.</li>
                                                   <li>[NAME] is the designated Grievance Officer in respect of the Platform. Any complaints or concerns with regards to any content on the Platform or any breach of this Agreement or Privacy Policy can be directed to the designated Grievance Officer in writing at Site Supply[ADDRESS], Haryana or through an email signed with the electronic signature sent to [EMAIL ADDRESS]</li>
                                                   </ul> <br>
                </div>
            </div>
        </div>
    </section>
@endsection